# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentledger < Formula
  desc "Cost attribution, budget enforcement, and financial observability for AI agents"
  homepage "https://github.com/WDZ-Dev/agent-ledger"
  version "0.1.0"
  license "LicenseRef-AgentLedger-SAL-1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WDZ-Dev/agent-ledger/releases/download/v0.1.0/agentledger_0.1.0_darwin_amd64.tar.gz"
      sha256 "3ea96c08ba443928a6afe469f2f5c38edf8d3b854ac045533f1a23961857dd4b"

      define_method(:install) do
        bin.install "agentledger"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WDZ-Dev/agent-ledger/releases/download/v0.1.0/agentledger_0.1.0_darwin_arm64.tar.gz"
      sha256 "f6b06f2b868522944bd496b3e6cb04c6dd919035719b4fe3f25d48173bf9f19b"

      define_method(:install) do
        bin.install "agentledger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WDZ-Dev/agent-ledger/releases/download/v0.1.0/agentledger_0.1.0_linux_amd64.tar.gz"
      sha256 "b752ef2235212872c0deeae8682c5437f89d8d6f587eaff3f14fb06b4f673ac8"
      define_method(:install) do
        bin.install "agentledger"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WDZ-Dev/agent-ledger/releases/download/v0.1.0/agentledger_0.1.0_linux_arm64.tar.gz"
      sha256 "cab018c166605cc07b438ea7cd43a2114e1b7737e29a9e266dd53037620a9df8"
      define_method(:install) do
        bin.install "agentledger"
      end
    end
  end

  test do
    system "#{bin}/agentledger", "--version"
  end
end
